### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by quavario** [iczer/vue-antd-admin#73]
npm install时报错如下
```
60331 silly saveTree     |   | `-- strip-bom@3.0.0
60331 silly saveTree     |   `-- path-type@2.0.0
60331 silly saveTree     +-- y18n@3.2.1
60331 silly saveTree     `-- yargs-parser@7.0.0
60331 silly saveTree       `-- camelcase@4.1.0
60332 warn ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
60333 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
60334 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
60335 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
60335 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
60335 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
60335 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
60336 verbose stack Error: leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
60336 verbose stack Exit status 1
60336 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
60336 verbose stack     at EventEmitter.emit (events.js:182:13)
60336 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
60336 verbose stack     at ChildProcess.emit (events.js:182:13)
60336 verbose stack     at maybeClose (internal/child_process.js:962:16)
60336 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
60337 verbose pkgid leveldown@3.0.0
60338 verbose cwd E:\Dev\git_repository\vue-antd-admin
60339 verbose Windows_NT 10.0.18363
60340 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
60341 verbose node v10.15.0
60342 verbose npm  v6.4.1
60343 error code ELIFECYCLE
60344 error errno 1
60345 error leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
60345 error Exit status 1
60346 error Failed at the leveldown@3.0.0 install script.
60346 error This is probably not a problem with npm. There is likely additional logging output above.
60347 verbose exit [ 1, true ]
```

**Comment by quavario** [comment]
`pouchdb`依赖的`leveldown`报错，更新后解决
